name: Bug Report
description: Create a report to help us improve EASL
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: EASL Version / Git Commit
      description: What version or commit hash are you running?
      placeholder: e.g. 0.1.0 or fb1f284
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'easl query "..."'
        2. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant logs or traceback.
      render: shell
